services:
  - type: web
    name: django-health-backend
    env: python
    plan: free
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt
      cd backend_health && python manage.py collectstatic --noinput
    startCommand: |
      cd backend_health && gunicorn backend_health.wsgi:application --workers 2
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend_health.settings
      - key: PYTHON_VERSION
        value: 3.9.7
