# Generated by Django 5.2 on 2025-07-01 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
    ]
