# Generated by Django 5.2 on 2025-07-02 12:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("health_app", "0003_alter_customuser_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
    ]
