# Generated by Django 5.2 on 2025-12-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_app", "0006_chatlog_session_id_conversationmemory"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatlog",
            index=models.Index(
                fields=["user", "timestamp"], name="health_app__user_id_75ea0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatlog",
            index=models.Index(
                fields=["user", "-timestamp"], name="health_app__user_id_7d59e2_idx"
            ),
        ),
    ]
