# Generated by Django 5.2 on 2025-12-02 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_app", "0007_chatlog_health_app__user_id_75ea0f_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExportRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "export_format",
                    models.CharField(
                        choices=[("JSON", "JSON"), ("PDF", "PDF")], max_length=10
                    ),
                ),
                (
                    "file_path",
                    models.FileField(blank=True, null=True, upload_to="exports/"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="SecurityAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login Attempt"),
                            ("LOGOUT", "Logout"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("DATA_EXPORT", "Data Export"),
                            ("DATA_DELETION", "Data Deletion"),
                            ("PROFILE_UPDATE", "Profile Update"),
                            ("ACCESS_DENIED", "Access Denied"),
                            ("SUSPICIOUS_ACTIVITY", "Suspicious Activity"),
                        ],
                        max_length=50,
                    ),
                ),
                ("success", models.BooleanField(default=True)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="health_app__user_id_041758_idx",
                    ),
                    models.Index(
                        fields=["event_type", "timestamp"],
                        name="health_app__event_t_b4c7e8_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="health_app__ip_addr_67b6a1_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity_type", models.CharField(max_length=100)),
                ("activity_details", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("session_id", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="health_app__user_id_2faf65_idx",
                    ),
                    models.Index(
                        fields=["activity_type", "timestamp"],
                        name="health_app__activit_17847e_idx",
                    ),
                ],
            },
        ),
    ]
